# Funding — Smart Pet Agent is MIT-licensed and free to use.
# Sponsorship is optional and purely additive; no feature is paywalled.

github: realstreetsmartnyc
open_collective: smart-pet-agent
ko_fi: smartpetagent
custom: ["https://www.streetsmartnyc.cloud/donate"]
